import React, { useState } from 'react';

const airportMap = {
    "rome": "FCO",
    "new york" : "JFK",
      "los angeles": "LAX",
      "london": "LHR",
      "tokyo": "HND",
      "paris": "CDG",
      "chicago": "ORD",
      "beijing": "PEK",
      "amsterdam": "AMS",
      "dubai": "DXB",
      "istanbul": "IST",
      "singapore": "SIN",
      "sydney": "SYD",
      "frankfurt": "FRA",
      "hong kong": "HKG",
      "madrid": "MAD",
      "toronto": "YYZ",
      "seoul": "ICN",
      "munich": "MUC",
      "san francisco": "SFO",
      "bangkok": "BKK",
      "shanghai": "PVG",
      "rome": "FCO",
      "delhi": "DEL",
      "vienna": "VIE",
      "zurich": "ZRH",
      "barcelona": "BCN",
      "copenhagen": "CPH",
      "osaka": "KIX",
      "moscow": "SVO",
      "mumbai": "BOM",
      "athens": "ATH",
      "lisbon": "LIS",
      "berlin": "TXL",
      "stockholm": "ARN",
      "dublin": "DUB",
      "doha": "DOH",
      "kuala lumpur": "KUL",
      "warsaw": "WAW",
      "brussels": "BRU",
      "vienna": "VIE",
      "munich": "MUC",
      "manchester": "MAN",
      "budapest": "BUD",
      "prague": "PRG",
      "marseille": "MRS",
      "nice": "NCE",
      "helsinki": "HEL",
      "geneva": "GVA",
      "cairo": "CAI",
      "johannesburg": "JNB",
      "istanbul": "IST",
      "lagos": "LOS",
      "nairobi": "NBO",
      "casablanca": "CMN",
      "lima": "LIM",
      "aao paulo": "GRU",
      "buenos aires": "EZE",
      "mexico city": "MEX",
      "toronto": "YYZ",
      "vancouver": "YVR",
      "montreal": "YUL",
      "calgary": "YYC",
      "melbourne": "MEL",
      "auckland": "AKL",
      "santiago": "SCL",
      "bogota": "BOG",
      "cape town": "CPT",
      "dubai": "DXB",
      "abu dhabi": "AUH",
      "doha": "DOH",
      "istanbul": "IST",
      "hong kong": "HKG",
      "singapore": "SIN",
      "bangkok": "BKK",
      "seoul": "ICN",
      "taipei": "TPE",
      "beijing": "PEK",
      "shanghai": "PVG",
      "tokyo": "HND",
      "sydney": "SYD",
      "auckland": "AKL",
      "johannesburg": "JNB",
      "cairo": "CAI",
      "nairobi": "NBO",
      "mumbai": "BOM",
      "new delhi": "DEL",
      "dublin": "DUB",
      "amsterdam": "AMS",
      "paris": "CDG",
      "frankfurt": "FRA",
      "london": "LHR",
      "madrid": "MAD",
      "rome": "FCO",
      "zurich": "ZRH",
      "vienna": "VIE",
      "stockholm": "ARN",
      "copenhagen": "CPH",
      "moscow": "SVO",
      "istanbul": "IST",
      "dubai": "DXB",
      "abu Dhabi": "AUH",
      "doha": "DOH",
      "kuala Lumpur": "KUL",
      "bangkok": "BKK",
      "milan": "MXP",
"venice": "VCE",
"florence": "FLR",
"naples": "NAP",
"bologna": "BLQ",
"palermo": "PMO",
"catania": "CTA",
"genoa": "GOA",
"pisa": "PSA",
"turin": "TRN",
"verona": "VRN",
"bari": "BRI",
"cagliari": "CAG",
"trieste": "TRS",
"brindisi": "BDS",
"lamezia terme": "SUF",
"reggio calabria": "REG",
"ancona": "AOI",
"perugia": "PEG",
"pescara": "PSR",
"olbia": "OLB",
"alghero": "AHO",
"rimini": "RMI",
"lecce": "LCC",
"bolzano": "BZO",
"trento": "ZIA",
"forlì": "FRL",
"siena": "SAY",
"matera": "BMT",
"mantua": "MNZ",
"parma": "PMF",
"urbino": "URB",
"ravello": "RVX",
"vicenza": "VIC",
"modena": "ZMO",
"lucca": "LCC",
"orvieto": "ORV",
"assisi": "AIZ",
"sorrento": "ZSJ",
"arezzo": "ZIT",
"cosenza": "ZCS",
"ascoli piceno": "APN",
"viterbo": "VTB",
"ferrara": "FRX",
"foggia": "FOG",
"livorno": "LIV",
"treviso": "TVS",
"sardinia": "SAR",
    
};

export default airportMap;